apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mondrianclientdeployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: mondrian
        tier: client
        track: test
    spec:
      containers:
        - name: mondrianclientcontainer
          image: "mondrian/client:1.0.0"
