apiVersion: v1
kind: Service
metadata:
  name: mondriansolrsvc
  labels:
    app: mondrian
    tier: searchindex
spec:
  selector:
    app: mondrian
    tier: searchindex
  ports:
    - port: 8983
      targetPort: 8983
---
apiVersion: v1
kind: Service
metadata:
  name: mondrianclientsvc
  labels:
    app: mondrian
    track: test
spec:
  selector:
    app: mondrian
    tier: client
    track: test
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mondrianclientdevsvc
  labels:
    app: mondrian
    track: dev
spec:
  selector:
    app: mondrian
    tier: client
    track: dev
  ports:
    - name: http
      nodePort: 30003
      port: 3000
      targetPort: 3000
  type: NodePort
