apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mondriansolrdeployment
spec:
  template:
    metadata:
      labels:
        app: mondrian
        tier: searchindex
    spec:
      containers:
        - name: mondriansolrcontainer
          image: "mondrian/solr:1.0.0"
          ports:
            - containerPort: 8983
