version: "3"
services:
  solr:
    build:
      context: ../
      dockerfile: docker/Dockerfile-solr
  dev-client:
    build:
      context: ../
      dockerfile: docker/Dockerfile-dev-client
    links:
      - "solr"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../:/app
  prod-client:
    build:
      context: ../
      dockerfile: docker/Dockerfile-prod-client
    links:
      - "solr"
    ports:
      - "9006:443"
