version: "3"
services:
  client:
    build:
      context: ../
      dockerfile: docker/Dockerfile-prod-client
    links:
      - "mondriansolrsvc"
    ports:
      - "443:443"
    restart: always
    volumes:
      - mondrian_facsimiles:/usr/share/nginx/html/static2
      - mondrian_secrets:/etc/nginx/ssl
volumes:
  mondrian_facsimiles:
  mondrian_secrets:
