FROM nginx:1.11.8-alpine

RUN apk add --no-cache --update openssl
RUN rm -rf /var/cache/apk/*

RUN mkdir -p /etc/nginx/ssl
RUN openssl req \
    -batch \
    -days 365 \
    -keyout /etc/nginx/ssl/nginx.key \
    -newkey rsa:2048 \
    -nodes \
    -out /etc/nginx/ssl/nginx.crt \
    -x509

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/.htpasswd /etc/nginx/.htpasswd
COPY dist /usr/share/nginx/html/build/
COPY static /usr/share/nginx/html/static/
COPY __entries__ /usr/share/nginx/html/__entries__/
COPY __notes__ /usr/share/nginx/html/__notes__/
COPY index.html /usr/share/nginx/html/index.html
COPY node_modules/react /usr/share/nginx/html/node_modules/react/
COPY node_modules/react-dom /usr/share/nginx/html/node_modules/react-dom/
