version: "3"
services:
  client:
    build:
      context: ../
      dockerfile: docker/Dockerfile-prod-client
    links:
      - "mondriansolrsvc"
    ports:
      - "443:443"
    volumes:
      - mondrian_facsimiles:/usr/share/nginx/html/static2
volumes:
  mondrian_facsimiles:
